### PR TITLE
Bump PL to 1.9.0

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
It seems like the python 3.11 upper bound is still required.

**Review by awaelchli — APPROVED** [review]

**Comment by Borda** [comment]
> It seems like the python 3.11 upper bound is still required.

PyTorch does not release for py3.11 yet

**Comment by Borda** [comment]
hi @hadim, an apology for the confusion and delays from our side... at the end we have finished adding all `1.8.{1,2,3,4,5,6}` releases and also fixed/merged #116 #115 Anyway, thank you for all your effort and help! :rabbit:

**Pull request closed without merging**
