### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jan-janssen**
As discussed in https://github.com/conda-forge/pytorch-lightning-feedstock/pull/129

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by Borda** [comment]
pls check https://github.com/Lightning-AI/lightning/blob/2.0.0/requirements/pytorch/base.txt and ignore all upper bounds :)

**Comment by jan-janssen** [comment]
> pls check https://github.com/Lightning-AI/lightning/blob/2.0.0/requirements/pytorch/base.txt and ignore all upper bounds :)

Why do you ignore the upper bounds? This is a bit confusing for me.

**Comment by Borda** [comment]
> Why do you ignore the upper bounds? This is a bit confusing for me.

it is set only for our CI so we have under control what is installed and it happened a few times that our dependency release version with breaking changes and suddenly, all development was blocked until we resolved this issue, not each update is conditioned with PR and all test need to pas so to say isolated... if you build the package you can see what real dependencies are :rabbit:

**Review by Borda — APPROVED** [review]

**Pull request merged**
