### PR TITLE
missing package

### PR DESCRIPTION
**Pull request by Borda**
successor of #8 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
This means that the solver can't find a combination of packages and versions that works together. Do you really need to pin the dependencies?

**Comment by Borda** [comment]
I have commented almost all versions and got to stage situation - that some packages/versions are missing on Conda
`pytorch-lightning 0.9.0 has requirement tensorboard==2.2.0, but you have tensorboard 2.3.0.`
pip has 2.2.0 but conda has closest 2.2.1
@CJ-Wright which seems that without a change in the released PL package we cannot get this build pass, right?

**Comment by CJ-Wright** [comment]
You can remove the pip check test if the package can be more flexible in it's tensorboard version than the pypi metadata indicates. Otherwise you can put in a PR into tensorboard to try to build 2.2.0. Note that the PR will need to be merged into a branch other than master, since it is behind the latest version.

**Comment by Borda** [comment]
@CJ-Wright thx, pls mind help mi understand the meta requirements, does it mean for anyone installing PL from conda-forge he has to meet this requirements, right?

**Comment by CJ-Wright** [comment]
It means that conda will install/upgrade/downgrade packages in in the environment PL is being installed into to match the requirements stated in the `meta.yaml`.

**Comment by Borda** [comment]
@CJ-Wright ok, mind check creating this PR? https://github.com/conda-forge/tensorboard-feedstock/pull/47 just needs to have another target branch, any suggestion for its name?

**Comment by Borda** [comment]
just for the record also adding tensorboard v2.2.1 - https://github.com/conda-forge/tensorboard-feedstock/pull/48

**Comment by CJ-Wright** [comment]
:tada:

**Pull request merged**
